spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memeAppDatabase
    username: memeApp
    password: memeAppPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
memesFolder: C:\\Users\\kalan\\OneDrive\\Pulpit\\Engineering project\\Memes\\
secretKey: 30AB367BFE6D126E6160145C72892B361E36DCD98E9A6385C354B282B69786A9

#server:
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/memeAppServer.p12
#    key-password: memeappserver
#    key-alias: memeAppServer
#    enabled: true